version: '3.8'

services:
  client:
    build:
      context: ../
      dockerfile: client/Dockerfile
    volumes:
      - ../:/workspace
      - /workspace/client/node_modules
    ports:
      - "3000:3000"
    working_dir: /workspace/client
    command: npm run dev
    depends_on:
      - server

  server:
    build:
      context: ../
      dockerfile: server/Dockerfile
    volumes:
      - ../:/workspace
      - /workspace/server/node_modules
    ports:
      - "4000:4000"
    working_dir: /workspace/server
    command: npm run dev
