version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./server:/app
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    volumes:
      - ./client:/app
    restart: unless-stopped
